#!/bin/bash
echo "Re-installing and enabling tty0tty"
cd
sudo apt update
sudo apt install build-essential
sudo apt install linux-headers-$(uname -r)
sudo git clone https://github.com/freemed/tty0tty.git
cd tty0tty
cd module
sudo make
sudo cp tty0tty.ko /lib/modules/$(uname -r)/kernel/drivers/misc/
sudo depmod
sudo modprobe tty0tty
sudo chmod 666 /dev/tnt0
sudo chmod 666 /dev/tnt1
